//! Error codes must stay inside this contract's reserved range (#1192).
use crate::Error;
use trivela_contract_errors::{assert_codes_in_domain, ContractDomain};

#[test]
fn error_codes_are_in_rewards_range() {
    assert_codes_in_domain(
        ContractDomain::Rewards,
        &[
            Error::Overflow as u32,
            Error::InsufficientBalance as u32,
            Error::Unauthorized as u32,
            Error::ContractPaused as u32,
            Error::CreditLimitExceeded as u32,
            Error::UnsupportedMigration as u32,
            Error::InvalidMultiplier as u32,
            Error::RateLimitExceeded as u32,
            Error::VestingNotFound as u32,
            Error::NoPendingAdmin as u32,
            Error::InsufficientReserve as u32,
            Error::InvalidRedemptionRate as u32,
            Error::InvalidAdminNonce as u32,
            Error::SelfReferral as u32,
            Error::CircularReferral as u32,
            Error::ReferralAlreadyRewarded as u32,
            Error::ReferralCapExceeded as u32,
            Error::ReferralNotConfigured as u32,
            Error::InvalidReferralConfig as u32,
            Error::ZeroReferralBonus as u32,
            Error::TokenModeNotEnabled as u32,
            Error::AllowanceExceeded as u32,
            Error::ApprovalExpired as u32,
            Error::InvalidExpiration as u32,
            Error::InvalidThreshold as u32,
            Error::InsufficientSignatures as u32,
            Error::NonceReused as u32,
            Error::DuplicateSigner as u32,
            Error::UnknownSigner as u32,
            Error::ZeroAmount as u32,
            Error::SelfTransfer as u32,
            Error::ClawbackNotFound as u32,
            Error::ClawbackTimelocked as u32,
            Error::ClawbackOverspend as u32,
            Error::ClawbackGuardianOnly as u32,
            Error::MultiSigNotConfigured as u32,
            Error::NotASigner as u32,
            Error::AlreadyApproved as u32,
            Error::ProposalNotFound as u32,
            Error::ProposalExpired as u32,
            Error::InsufficientApprovals as u32,
            Error::GovernanceNotConfigured as u32,
            Error::ProposalAlreadyPending as u32,
            Error::TimeLockActive as u32,
            Error::ProposalCancelled as u32,
            Error::AirdropRootNotSet as u32,
            Error::AirdropInvalidProof as u32,
            Error::AirdropNullifierUsed as u32,
            Error::InvalidDistributionMode as u32,
            Error::BelowMinClaim as u32,
            Error::InvalidBoostCurve as u32,
            Error::ZeroBoostMultiplier as u32,
            Error::InvalidLockSchedule as u32,
            Error::BelowMinClaim as u32,
            Error::CampaignSupplyCapExceeded as u32,
            Error::InvalidSupplyCap as u32,
            Error::InvalidReferralDepth as u32,
            Error::InvalidReferralTierConfig as u32,
            Error::InvalidBoostCurve as u32,
            Error::InvalidLockSchedule as u32,
            Error::ZeroBoostMultiplier as u32,
            Error::OperatorBudgetExceeded as u32,
            Error::OperatorDelegationNotFound as u32,
            Error::InvalidOperatorDelegation as u32,
            Error::RedemptionAssetNotFound as u32,
            Error::RedemptionAssetDisabled as u32,
            Error::InvalidAssetConfig as u32,
            Error::ClaimCooldownActive as u32,
            Error::InvalidCooldownConfig as u32,
        ],
    );
}
