// @ts-check
/**
 * OpenAPI path items for router-mounted endpoints that `openapi.yaml` does not
 * describe yet (#1259). `buildOpenApiDocument` merges these into the served
 * document at `/docs/api` without overriding anything hand-written, so the
 * checked-in spec (and the SDK generated from it) is left untouched.
 */

const idParam = {
  name: 'id',
  in: 'path',
  required: true,
  description: 'Campaign ID',
  schema: { type: 'string' },
};
const jobIdParam = {
  name: 'jobId',
  in: 'path',
  required: true,
  description: 'Export job ID',
  schema: { type: 'string', format: 'uuid' },
};

const errorBody = {
  content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } },
};
const notFound = { description: 'Not found', ...errorBody };
const badRequest = { description: 'Invalid request', ...errorBody };
const unauthorized = { description: 'Missing or invalid API key', ...errorBody };

const apiKey = [{ ApiKeyAuth: [] }];
const masterKey = [{ ApiKeyAuth: [] }];

const exportJob = {
  type: 'object',
  properties: {
    jobId: { type: 'string', format: 'uuid' },
    campaignId: { type: 'string' },
    format: { type: 'string', enum: ['csv', 'json'] },
    status: { type: 'string', enum: ['queued', 'running', 'completed', 'failed'] },
    from: { type: 'string', nullable: true },
    to: { type: 'string', nullable: true },
    rowCount: { type: 'integer', nullable: true },
    downloadUrl: { type: 'string', format: 'uri', nullable: true },
    error: { type: 'string', nullable: true },
    createdAt: { type: 'string', format: 'date-time' },
    startedAt: { type: 'string', format: 'date-time', nullable: true },
    completedAt: { type: 'string', format: 'date-time', nullable: true },
    statusUrl: { type: 'string' },
  },
};

const fraudFlag = {
  type: 'object',
  properties: {
    id: { type: 'integer' },
    campaignId: { type: 'string' },
    rule: { type: 'string', enum: ['ip_subnet_cluster', 'proxy_exit_node'] },
    subject: { type: 'string', description: 'The IP subnet (/24, /64) or proxy exit node' },
    accountCount: { type: 'integer' },
    accounts: { type: 'array', items: { type: 'string' } },
    status: { type: 'string', enum: ['open', 'dismissed', 'confirmed'] },
    firstSeenAt: { type: 'string', format: 'date-time' },
    lastSeenAt: { type: 'string', format: 'date-time' },
  },
};

const deposit = {
  type: 'object',
  properties: {
    id: { type: 'integer' },
    account: { type: 'string' },
    from: { type: 'string', nullable: true },
    assetCode: { type: 'string' },
    assetIssuer: { type: 'string', nullable: true },
    amount: { type: 'string' },
    txHash: { type: 'string' },
    verified: { type: 'boolean' },
    observedAt: { type: 'string', format: 'date-time' },
    recordedAt: { type: 'string', format: 'date-time' },
  },
};

/** @param {Record<string, any>} schema @param {string} description */
const json = (schema, description) => ({
  description,
  content: { 'application/json': { schema } },
});

/** @type {Record<string, Record<string, any>>} */
export const ADDITIONAL_PATHS = {
  '/api/v1/campaigns/{id}/exports': {
    post: {
      summary: 'Queue an asynchronous campaign export',
      description:
        'Queues a CSV/JSON export that is generated by a background worker, so large campaigns do not time out. Poll the returned `statusUrl` until `status` is `completed`, then download from `downloadUrl`.',
      tags: ['Campaigns'],
      operationId: 'createCampaignExport',
      security: apiKey,
      parameters: [idParam],
      requestBody: {
        required: false,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                format: { type: 'string', enum: ['csv', 'json'], default: 'csv' },
                from: { type: 'string', format: 'date-time' },
                to: { type: 'string', format: 'date-time' },
              },
            },
          },
        },
      },
      responses: {
        202: json(exportJob, 'Export queued'),
        400: badRequest,
        401: unauthorized,
        404: notFound,
      },
    },
    get: {
      summary: 'List recent exports for a campaign',
      tags: ['Campaigns'],
      operationId: 'listCampaignExports',
      security: apiKey,
      parameters: [
        idParam,
        { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100 } },
      ],
      responses: {
        200: json(
          {
            type: 'object',
            properties: {
              data: { type: 'array', items: exportJob },
              total: { type: 'integer' },
            },
          },
          'Most recent exports, newest first',
        ),
        401: unauthorized,
        404: notFound,
      },
    },
  },
  '/api/v1/campaigns/{id}/exports/{jobId}': {
    get: {
      summary: 'Get the status of a campaign export',
      tags: ['Campaigns'],
      operationId: 'getCampaignExport',
      security: apiKey,
      parameters: [idParam, jobIdParam],
      responses: { 200: json(exportJob, 'Export job'), 401: unauthorized, 404: notFound },
    },
  },
  '/api/v1/admin/fraud/flags': {
    get: {
      summary: 'List fraud flags',
      description:
        'Flags raised when several distinct accounts sign up from one IP subnet or proxy exit node. Requires the master key.',
      tags: ['Admin'],
      operationId: 'listFraudFlags',
      security: masterKey,
      parameters: [
        {
          name: 'status',
          in: 'query',
          schema: { type: 'string', enum: ['open', 'dismissed', 'confirmed'] },
        },
        { name: 'campaignId', in: 'query', schema: { type: 'string' } },
        { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 200 } },
        { name: 'offset', in: 'query', schema: { type: 'integer', minimum: 0 } },
      ],
      responses: {
        200: json(
          {
            type: 'object',
            properties: { data: { type: 'array', items: fraudFlag }, total: { type: 'integer' } },
          },
          'Fraud flags, newest activity first',
        ),
        400: badRequest,
        401: unauthorized,
      },
    },
  },
  '/api/v1/admin/fraud/flags/{id}': {
    patch: {
      summary: 'Review a fraud flag',
      tags: ['Admin'],
      operationId: 'updateFraudFlag',
      security: masterKey,
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'integer' } }],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: ['status'],
              properties: { status: { type: 'string', enum: ['open', 'dismissed', 'confirmed'] } },
            },
          },
        },
      },
      responses: {
        200: json(fraudFlag, 'Updated flag'),
        400: badRequest,
        401: unauthorized,
        404: notFound,
      },
    },
  },
  '/api/v1/operator/deposits': {
    get: {
      summary: 'List observed operator deposits',
      description:
        'Reward-token deposits seen on the watched custody accounts. Requires the master key.',
      tags: ['Admin'],
      operationId: 'listOperatorDeposits',
      security: masterKey,
      parameters: [
        { name: 'account', in: 'query', schema: { type: 'string' } },
        { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 200 } },
        { name: 'beforeId', in: 'query', schema: { type: 'integer' } },
      ],
      responses: {
        200: json(
          {
            type: 'object',
            properties: { data: { type: 'array', items: deposit }, total: { type: 'integer' } },
          },
          'Deposits, newest first',
        ),
        401: unauthorized,
      },
    },
  },
  '/api/v1/operator/deposits/{txHash}': {
    get: {
      summary: 'Verify a deposit by transaction hash',
      tags: ['Admin'],
      operationId: 'getOperatorDeposit',
      security: masterKey,
      parameters: [{ name: 'txHash', in: 'path', required: true, schema: { type: 'string' } }],
      responses: {
        200: json(
          {
            type: 'object',
            properties: {
              txHash: { type: 'string' },
              verified: { type: 'boolean' },
              deposits: { type: 'array', items: deposit },
            },
          },
          'Deposits recorded for the transaction',
        ),
        401: unauthorized,
        404: notFound,
      },
    },
  },
  '/api/v1/operator/watcher/status': {
    get: {
      summary: 'Horizon deposit watcher status',
      tags: ['Admin'],
      operationId: 'getDepositWatcherStatus',
      security: masterKey,
      responses: {
        200: json(
          {
            type: 'object',
            properties: {
              running: { type: 'boolean' },
              depositsRecorded: { type: 'integer' },
              duplicates: { type: 'integer' },
              errors: { type: 'integer' },
              accounts: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    account: { type: 'string' },
                    connected: { type: 'boolean' },
                    reconnectAttempts: { type: 'integer' },
                    lastEventAt: { type: 'string', nullable: true },
                    cursor: { type: 'string', nullable: true },
                  },
                },
              },
            },
          },
          'Watcher health',
        ),
        401: unauthorized,
      },
    },
  },
};
